/serial:
  ros__parameters:
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/gimbal_control:
  ros__parameters:
    pid_kp_x: 0.0
    pid_ki_x: 0.002
    pid_kd_x: 0.0
    pid_i_max_x: 0.0
    pid_out_max_x: 1.0
    pid_mode_x: delta
    pid_kp_y: 0.0
    pid_ki_y: 0.002
    pid_kd_y: 0.0
    pid_i_max_y: 0.0
    pid_out_max_y: 1.0
    pid_mode_y: delta